#!/bin/bash

# This file is part of luax-releases.
#
# luax-releases is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# luax-releases is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with luax-releases.  If not, see <https://www.gnu.org/licenses/>.
#
# For further information about luax-releases you can visit
# https://github.com/CDSoft/luax-releases

set -eu

export PREFIX=$PWD/local
DATE=$(date +%Y_%m_%d)
RELEASE=$PWD/luax-release/$DATE

TARGETS=(
    lua
    linux-x86_64
    linux-x86_64-musl
    linux-aarch64
    linux-aarch64-musl
    macos-x86_64
    macos-aarch64
    windows-x86_64
)

all()
{
    for target in "${TARGETS[@]}"
    do
        "$@" "$target"
    done
}

gitclone()
{
    local URL="$1"
    local DEST="${2:-$(basename "$URL")}"
    if [ -d "$DEST" ]
    then
        ( cd "$DEST" && git pull )
    else
        git clone "$URL" "$DEST"
    fi
}

#####################################################################
# LuaX cross-compilers to build other LuaX softwares
#####################################################################

mkdir -p "$PREFIX"

gitclone https://github.com/cdsoft/luax luax-cross
( cd luax-cross && ./bootstrap.sh cross nossl small && ninja compile && ninja install)

luax-cross-env()
{
    eval "$(luax-cross/.build/bin/luax env)"
}

gitclone https://github.com/cdsoft/luax luax-cross-ssl
( cd luax-cross-ssl && ./bootstrap.sh cross ssl small && ninja compile)

luax-cross-ssl-env()
{
    eval "$(luax-cross-ssl/.build/bin/luax env)"
}

#####################################################################
# LuaX release
#####################################################################

gitclone https://github.com/cdsoft/luax
( cd luax && ./bootstrap.sh release fast ssl)

LUAX_VERSION=$(cd luax && git describe --tags)

add()
{
    local NAME="$1"
    local VERSION="$2"
    local ARCH="$3"
    mkdir -p  "$RELEASE/luax-$DATE-$ARCH"
    tar xaf "$NAME/.build/release/$VERSION/$NAME-$VERSION-$ARCH.tar.gz" -C "$RELEASE/luax-$DATE-$ARCH" --strip-components=1
}

all add luax "$LUAX_VERSION"

#####################################################################
# bang release
#####################################################################

gitclone https://github.com/cdsoft/bang
luax-cross-ssl-env
( cd bang && ./boot.lua && ninja release && ninja install)

BANG_VERSION=$(cd bang && git describe --tags)

all add bang "$BANG_VERSION"

#####################################################################
# ypp release
#####################################################################

gitclone https://github.com/cdsoft/ypp
luax-cross-ssl-env
( cd ypp && bang && ninja release && ninja install)

YPP_VERSION=$(cd ypp && git describe --tags)

all add ypp "$YPP_VERSION"

#####################################################################
# panda release
#####################################################################

gitclone https://github.com/cdsoft/panda
luax-cross-env
( cd panda && bang && ninja release && ninja install)

add_panda()
{
    local NAME="$1"
    local VERSION="$2"
    local ARCH="$3"
    tar xaf "$NAME/.build/release/$VERSION/$NAME-$VERSION.tar.gz" -C "$RELEASE/luax-$DATE-$ARCH" --strip-components=1
}

PANDA_VERSION=$(cd panda && git describe --tags)

all add_panda panda "$PANDA_VERSION"

#####################################################################
# lsvg release
#####################################################################

gitclone https://github.com/cdsoft/lsvg
luax-cross-ssl-env
( cd lsvg && bang && ninja release && ninja install)

LSVG_VERSION=$(cd lsvg && git describe --tags)

all add lsvg "$LSVG_VERSION"

#####################################################################
# ICD release
#####################################################################

gitclone https://github.com/cdsoft/icd
luax-cross-env
( cd icd && bang && ninja release && ninja install)

ICD_VERSION=$(cd icd && git describe --tags)

all add icd "$ICD_VERSION"

#####################################################################
# tagref release
#####################################################################

gitclone https://github.com/cdsoft/tagref
luax-cross-env
( cd tagref && bang && ninja release && ninja install)

TAGREF_VERSION=$(cd tagref && git describe --tags)

all add tagref "$TAGREF_VERSION"

#####################################################################
# calculadoira release
#####################################################################

gitclone https://github.com/cdsoft/calculadoira
luax-cross-env
( cd calculadoira && bang && ninja release && ninja install)

CALCULADOIRA_VERSION=$(cd calculadoira && git describe --tags)

all add calculadoira "$CALCULADOIRA_VERSION"

#####################################################################
# Archives
#####################################################################

archive()
{
    local ARCH="$1"
    tar -caf "$RELEASE/luax-$DATE-$ARCH.tar.xz" -C "$RELEASE" "luax-$DATE-$ARCH"
}

all archive

cat <<EOF | pandoc --to gfm > "$RELEASE/README.md"
# LuaX and friends binary release - $DATE

| Project       | Version                                                                                               | Sources                                                       |
| ------------- | ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------- |
| LuaX          | [$LUAX_VERSION](https://github.com/CDSoft/luax/releases/tag/$LUAX_VERSION)                            | [CDSoft/luax](https://github.com/CDSoft/luax)                 |
| bang          | [$BANG_VERSION](https://github.com/CDSoft/bang/releases/tag/$BANG_VERSION)                            | [CDSoft/bang](https://github.com/CDSoft/bang)                 |
| ypp           | [$YPP_VERSION](https://github.com/CDSoft/ypp/releases/tag/$YPP_VERSION)                               | [CDSoft/ypp](https://github.com/CDSoft/ypp)                   |
| panda         | [$PANDA_VERSION](https://github.com/CDSoft/panda/releases/tag/$PANDA_VERSION)                         | [CDSoft/panda](https://github.com/CDSoft/panda)               |
| lsvg          | [$LSVG_VERSION](https://github.com/CDSoft/lsvg/releases/tag/$LSVG_VERSION)                            | [CDSoft/lsvg](https://github.com/CDSoft/lsvg)                 |
| icd           | [$ICD_VERSION](https://github.com/CDSoft/icd/releases/tag/$ICD_VERSION)                               | [CDSoft/icd](https://github.com/CDSoft/icd)                   |
| tagref        | [$TAGREF_VERSION](https://github.com/CDSoft/tagref/releases/tag/$TAGREF_VERSION)                      | [CDSoft/tagref](https://github.com/CDSoft/tagref)             |
| calculadoira  | [$CALCULADOIRA_VERSION](https://github.com/CDSoft/calculadoira/releases/tag/$CALCULADOIRA_VERSION)    | [CDSoft/calculadoira](https://github.com/CDSoft/calculadoira) |
EOF
